FROM python

WORKDIR /app

RUN python -m pip install --upgrade pip
RUN python -m pip install poetry

COPY . .

RUN python -m poetry install

EXPOSE 10443
CMD ["python", "-m", "poetry", "run", "gunicorn", "-w", "2", "-b", ":10443", "src.app:app"]