[tool.poetry]
name = "oxygen"
version = "0.1.0"
description = "DMJam internet ranking web app"
authors = ["Minseok Chu <mchu7797@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyodbc = "^5.0.1"
Flask = "^3.0.0"
Flask-Cors = "^4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
