[tool.poetry]
name = "Oxygen"
version = "0.1.0"
description = "O2Jam internet ranking server project"
authors = ["Chu Minseok <mchu7797@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Flask = "^3.0.0"
Flask-Cors = "^4.0.0"
pyodbc = "^5.0.1"
waitress = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
