name: Remote SSH Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: deploy to server
    runs-on: ubuntu-latest
    steps:
    - name: execute update script
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        username: ${{ secrets.SERVER_ACCOUNT_ID }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: cd C:\ServerPackage\Scoreboard\Oxygen && update.bat
